### ISSUE TITLE
The link to Github repo on NPM page is broken

### ISSUE THREAD

**Issue by arturi** [sapegin/richtypo.js#18]
https://www.npmjs.com/package/richtypo

The link should be: https://github.com/sapegin/richtypo.js

**Comment by sapegin** [comment]
Fixed.

(For such tiny things it’s much easier to just send a PR than to describe the problem in an issue.)

**Comment by arturi** [comment]
Where do I fix the link on NPM page? Is it taken from package.json or specified manually somehow?

The problem still persists as of right now:

<img width="393" alt="screen shot 2015-09-23 at 13 27 52" src="https://cloud.githubusercontent.com/assets/1199054/10042865/1188ac38-61f7-11e5-9b4e-74b7ff8c0b9a.png">
